name: Build PlatformIO project
on:
  pull_request:
    # This will trigger the workflow for any label event on a pull request.
    types:
      - labeled

jobs:
  build:
    if: contains(github.event.label.name, 'ci-check') || github.event.label.name == 'ci-check'
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup PlatformIO in PATH
      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1

      # Build the PlatformIO project
      - name: Build PlatformIO project
        run: pio run